-- Final Fix: Treat BOTH products.id and destinations.id as UUIDs
-- Based on error messages, both tables use UUID primary keys.

-- 1. Fix 'reviews' table columns
DO $$
BEGIN
    -- Fix product_id (Drop if not UUID)
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reviews' AND column_name = 'product_id' AND data_type != 'uuid') THEN
        ALTER TABLE public.reviews DROP COLUMN product_id;
    END IF;

    -- Fix destination_id (Drop if not UUID)
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reviews' AND column_name = 'destination_id' AND data_type != 'uuid') THEN
        ALTER TABLE public.reviews DROP COLUMN destination_id;
    END IF;

    -- Add columns with UUID type
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reviews' AND column_name = 'product_id') THEN
        ALTER TABLE public.reviews ADD COLUMN product_id uuid REFERENCES public.products(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reviews' AND column_name = 'destination_id') THEN
        ALTER TABLE public.reviews ADD COLUMN destination_id uuid REFERENCES public.destinations(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 2. Create 'favorites' table with UUIDs for BOTH foreign keys
CREATE TABLE IF NOT EXISTS public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid REFERENCES auth.users NOT NULL,
  product_id uuid REFERENCES public.products(id) ON DELETE CASCADE,
  destination_id uuid REFERENCES public.destinations(id) ON DELETE CASCADE, -- Changed to UUID
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(user_id, product_id),
  UNIQUE(user_id, destination_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage their own favorites" ON public.favorites;
CREATE POLICY "Users can manage their own favorites" ON public.favorites USING (auth.uid() = user_id);

-- 3. Create 'notifications' table (Standard)
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid REFERENCES auth.users NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL, 
  is_read boolean DEFAULT false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own notifications" ON public.notifications;
CREATE POLICY "Users can view their own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);

-- 4. Create 'categories' table (Standard)
CREATE TABLE IF NOT EXISTS public.categories (
  id bigint generated by default as identity primary key,
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  icon text, 
  type text, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Everyone can read categories" ON public.categories;
CREATE POLICY "Everyone can read categories" ON public.categories FOR SELECT USING (true);

-- Defaut Categories
INSERT INTO public.categories (name, slug, type) VALUES
('Makanan', 'makanan', 'product'),
('Minuman', 'minuman', 'product'),
('Kerajinan', 'kerajinan', 'product'),
('Fashion', 'fashion', 'product'),
('Oleh-oleh', 'oleh-oleh', 'product'),
('Batik', 'batik', 'product'),
('Wisata Alam', 'wisata-alam', 'wisata'),
('Wisata Budaya', 'wisata-budaya', 'wisata'),
('Wisata Edukasi', 'wisata-edukasi', 'wisata')
ON CONFLICT (name) DO NOTHING;
