-- Fix for type mismatches (BigInt vs UUID)
-- We assume products.id is UUID and destinations.id is BigInt (based on schema.sql 'wisata')

-- 1. Fix 'reviews' table columns if they were created incorrectly
DO $$
BEGIN
    -- Check if product_id exists and is not UUID, then drop/convert it? 
    -- Safer to just drop and re-add if empty, or alter type.
    -- Since this is dev, we'll try to alter.
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'reviews' AND column_name = 'product_id' AND data_type != 'uuid'
    ) THEN
        ALTER TABLE public.reviews DROP COLUMN product_id;
    END IF;

    -- Re-add with correct type if missing
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'reviews' AND column_name = 'product_id'
    ) THEN
        ALTER TABLE public.reviews ADD COLUMN product_id uuid REFERENCES public.products(id) ON DELETE CASCADE;
    END IF;

    -- Check destinations (assuming bigint is correct based on previous error NOT mentioning it, but let's be careful)
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'reviews' AND column_name = 'destination_id'
    ) THEN
        ALTER TABLE public.reviews ADD COLUMN destination_id bigint REFERENCES public.destinations(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 2. Create 'favorites' / 'wishlists' table with CORRECT TYPES
CREATE TABLE IF NOT EXISTS public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid REFERENCES auth.users NOT NULL,
  product_id uuid REFERENCES public.products(id) ON DELETE CASCADE, -- Changed to UUID
  destination_id bigint REFERENCES public.destinations(id) ON DELETE CASCADE, -- Kept as BigInt
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(user_id, product_id),
  UNIQUE(user_id, destination_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

-- Drop exist policies to avoid creation errors if re-running
DROP POLICY IF EXISTS "Users can manage their own favorites" ON public.favorites;
CREATE POLICY "Users can manage their own favorites"
ON public.favorites
USING (auth.uid() = user_id);

-- 3. Create 'notifications' table (No changes needed, but included for completeness if failed previously)
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid REFERENCES auth.users NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL, 
  is_read boolean DEFAULT false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own notifications" ON public.notifications;
CREATE POLICY "Users can view their own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);

-- 4. Create 'categories' table
CREATE TABLE IF NOT EXISTS public.categories (
  id bigint generated by default as identity primary key,
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  icon text, 
  type text, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Everyone can read categories" ON public.categories;
CREATE POLICY "Everyone can read categories" ON public.categories FOR SELECT USING (true);

-- Insert default categories if not exists
INSERT INTO public.categories (name, slug, type) VALUES
('Makanan', 'makanan', 'product'),
('Minuman', 'minuman', 'product'),
('Kerajinan', 'kerajinan', 'product'),
('Fashion', 'fashion', 'product'),
('Oleh-oleh', 'oleh-oleh', 'product'),
('Batik', 'batik', 'product'),
('Wisata Alam', 'wisata-alam', 'wisata'),
('Wisata Budaya', 'wisata-budaya', 'wisata'),
('Wisata Edukasi', 'wisata-edukasi', 'wisata')
ON CONFLICT (name) DO NOTHING;
