-- 1. Updates to the 'reviews' table
-- Ensure it supports both products and destinations
ALTER TABLE public.reviews
ADD COLUMN IF NOT EXISTS product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS destination_id bigint REFERENCES public.destinations(id) ON DELETE CASCADE;

-- 2. Create 'favorites' / 'wishlists' table
CREATE TABLE IF NOT EXISTS public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid REFERENCES auth.users NOT NULL,
  product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
  destination_id bigint REFERENCES public.destinations(id) ON DELETE CASCADE,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(user_id, product_id), -- Prevent duplicate favorites for same product
  UNIQUE(user_id, destination_id) -- Prevent duplicate favorites for same destination
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can create their own favorites"
ON public.favorites FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own favorites"
ON public.favorites FOR SELECT TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own favorites"
ON public.favorites FOR DELETE TO authenticated
USING (auth.uid() = user_id);

-- 3. Create 'notifications' table
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid REFERENCES auth.users NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL, -- 'order_update', 'promo', 'system'
  is_read boolean DEFAULT false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own notifications"
ON public.notifications FOR SELECT TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can update (read) their own notifications"
ON public.notifications FOR UPDATE TO authenticated
USING (auth.uid() = user_id);

-- 4. Create 'categories' table
CREATE TABLE IF NOT EXISTS public.categories (
  id bigint generated by default as identity primary key,
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  icon text, -- URL or icon name
  type text, -- 'product' or 'wisata'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Everyone can read categories"
ON public.categories FOR SELECT
USING (true);

-- Insert default categories
INSERT INTO public.categories (name, slug, type) VALUES
('Makanan', 'makanan', 'product'),
('Minuman', 'minuman', 'product'),
('Kerajinan', 'kerajinan', 'product'),
('Fashion', 'fashion', 'product'),
('Oleh-oleh', 'oleh-oleh', 'product'),
('Batik', 'batik', 'product'),
('Wisata Alam', 'wisata-alam', 'wisata'),
('Wisata Budaya', 'wisata-budaya', 'wisata'),
('Wisata Edukasi', 'wisata-edukasi', 'wisata')
ON CONFLICT (name) DO NOTHING;
