-- Create the table for tourism spots
create table public.wisata (
  id bigint generated by default as identity primary key,
  name text not null,
  type text,
  description text,
  image_url text,
  rating float4,
  has_ar boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.wisata enable row level security;

-- Create a policy that allows everyone to read data
create policy "Enable read access for all users"
on public.wisata
for select
using (true);

-- Insert mock data
insert into public.wisata (name, type, description, image_url, rating, has_ar)
values
  (
    'Air Terjun Widuri',
    'Wisata Alam',
    'Air terjun setinggi 40 meter yang dikelilingi hutan jati rindang. Cocok untuk bermain air dan berkemah.',
    'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    4.5,
    false
  ),
  (
    'Bledug Kuwu',
    'Wisata Alam',
    'Fenomena alam unik berupa letupan lumpur yang mengandung garam, mirip dengan kawah lumpur.',
    'https://jatimterkini.com/wp-content/uploads/2024/09/Pic-1-1.jpg',
    4.6,
    true
  ),
  (
    'Waduk Nglangon',
    'Wisata Alam',
    'Waduk bersejarah peninggalan Belanda dengan panorama hutan jati dan spot sunset yang indah.',
    'https://images.unsplash.com/photo-1651079047808-1375d415fe85?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    4.2,
    false
  ),
  (
    'Api Abadi Mrapen',
    'Wisata Alam',
    'Sumber api alam yang tidak pernah padam, sering digunakan untuk menyalakan obor pesta olahraga.',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Mrapen_Eternal_Flame.jpg/1200px-Mrapen_Eternal_Flame.jpg',
    4.7,
    true
  ),
  (
    'Candi Joglo',
    'Cagar Budaya',
    'Bangunan bernuansa Bali dan Jawa yang unik, menawarkan spot foto instagramable dan nilai budaya.',
    'https://images.unsplash.com/photo-1566559631133-969041fc5583?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    4.4,
    true
  ),
  (
    'Waduk Kedung Ombo',
    'Wisata Alam',
    'Waduk raksasa yang menawarkan wisata air, pemancingan, dan kuliner ikan bakar yang lezat.',
    'https://upload.wikimedia.org/wikipedia/commons/6/66/Kedung_Ombo_Dam.jpg',
    4.5,
    false
  ),
  (
    'White Canyon (Tugu Lasi)',
    'Wisata Alam',
    'Tebing kapur putih yang eksotis, sisa aktivitas pertambangan yang kini menjadi spot foto menarik.',
    'https://asset.kompas.com/crops/Oq6X9j4X9j4X9j4X9j4X9j4X9j4=/0x0:0x0/750x500/data/photo/2020/09/23/5f6b3b3b3b3b3.jpg',
    4.3,
    false
  ),
  (
    'Ayodya Bloombang Waterpark',
    'Wisata Keluarga',
    'Taman rekreasi air modern dengan berbagai wahana seru untuk keluarga dan anak-anak.',
    'https://images.unsplash.com/photo-1576439562016-c8126365707a?auto=format&fit=crop&q=80&w=800',
    4.4,
    false
  ),
  (
    'Desa Wisata Banjarejo',
    'Wisata Edukasi',
    'Desa wisata yang terkenal dengan penemuan fosil purba dan patung Ganesha Tidur raksasa.',
    'https://images.unsplash.com/photo-1605218427368-35b0f996963f?auto=format&fit=crop&q=80&w=800',
    4.6,
    false
  ),
  (
    'Jati Pohon Indah',
    'Wisata Alam',
    'Bukit pandang dengan pemandangan kota Purwodadi dari ketinggian, sangat indah saat malam hari.',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=800',
    4.5,
    false
  );

-- Create admin table
create table public.admin (
  id uuid references auth.users not null primary key,
  email text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for admin table
alter table public.admin enable row level security;

-- Create policy to allow read access for authenticated users (to check if they are admin)
create policy "Enable read access for authenticated users"
on public.admin
for select
to authenticated
using (true);

-- Create policy to allow insert for service role only (used by create-admin script)
create policy "Enable insert for service role only"
on public.admin
for insert
to service_role
with check (true);
